#! /usr/bin/env python

from argparse import ArgumentParser as argpars

parser = argpars(description='Read aims geometry files and store in TDEP infile.positions')
parser.add_argument('geoms', type=str, nargs='+', help='geometry input files')
args = parser.parse_args()

positions = []

for geom in args.geoms:
    print('  file being processed: {:s}'.format(geom))
    with open(geom, 'r') as f:
        lines = f.readlines()

    for ll in lines:
        if 'atom ' in ll:
          print('Please use fractional coordinates. Break.')
          exit()
        if 'atom_frac' in ll:
            positions.append(ll.split()[1:4])
print(f'  \nnumber of geometries extracted: {len(positions)} ' +
        f'(= {len(args.geoms)} * {len(positions) / len(args.geoms):.0f})')

with open('infile.positions', 'w') as f:
    for pos in positions:
        f.write('{:s} {:s} {:s}\n'.format(*tuple(pos)))

print('  infile.positions written.\n')
